<?php session_start(); ?>
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>PLMUN Portal</title>
  <link rel="stylesheet" href="../../assets/css/student.css" />
  <!-- PLMUN Logo -->
  <link
    rel="apple-touch-icon"
    sizes="180x180"
    href="../../assets/images/apple-touch-icon.png" />
  <link
    rel="icon"
    type="image/png"
    sizes="32x32"
    href="../../assets/images/favicon-32x32.png" />
  <link
    rel="icon"
    type="image/png"
    sizes="16x16"
    href="../../assets/images/favicon-16x16.png" />
  <link rel="manifest" href="../../assets/images/site.webmanifest" />
</head>
<body>
  <div class="dashboard-container">
    <!-- Sidebar -->
    <aside class="sidebar">
      <div class="sidebar-header">
        <span class="plmun">PLMUN</span><span class="portal">Portal</span>
        <p class="role-label">Student</p>
      </div>
      <nav class="sidebar-nav">
        <span class="nav-section-title">General</span>
        <ul>
          <li class="active"><a href="#dashboard">Dashboard</a></li>
          <li><a href="#grades">Grade Breakdown</a></li>
          <li><a href="#insights">Performance Insights</a></li>
          <li><a href="#progress">Progress Tracker</a></li>
          <li><a href="#notifications">Notifications</a></li>
          <li><a href="#quizzes">AI Quizzes</a></li>
        </ul>
      </nav>
      <div class="sidebar-footer">
        <a href="../login.php" class="logout">Log Out</a>
      </div>
    </aside>

    <!-- Main Content -->
    <main class="main-content">
      <header class="main-header">
        <h1>Student Dashboard</h1>
        <div class="user-profile">
          <span>
            <?php echo $_SESSION['user_name'] ?? 'Guest'; ?>
            (<?php echo $_SESSION['role'] ?? 'Role'; ?>)
          </span>
          <img src="../../assets/images/Thug.jpg" alt="User Avatar" />
        </div>
      </header>

      <div class="content-body">
        <!-- ================= DASHBOARD ================= -->
        <section id="dashboard" class="tab-section active">
          <h2>Visual Grade Summary</h2>
          <div class="cards-container">
            <div class="card">
              <h4>Current GPA</h4>
              <p class="metric">3.45</p>
              <span>Updated this semester</span>
            </div>
            <div class="card">
              <h4>Subjects Passed</h4>
              <p class="metric">24</p>
              <span>Overall</span>
            </div>
            <div class="card">
              <h4>At-Risk Subjects</h4>
              <p class="metric error">2</p>
              <span>Needs improvement</span>
            </div>
          </div>
        </section>

        <!-- ================= GRADE BREAKDOWN ================= -->
        <section id="grades" class="tab-section hidden">
          <h2>Grade Breakdown</h2>
          <table>
            <thead>
              <tr>
                <th>Subject</th>
                <th>Activity</th>
                <th>Score</th>
                <th>Weight</th>
                <th>Final Grade</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>IT 101</td>
                <td>Midterm Exam</td>
                <td>85/100</td>
                <td>40%</td>
                <td>34/40</td>
              </tr>
            </tbody>
          </table>
        </section>

        <!-- ================= PERFORMANCE INSIGHTS ================= -->
        <section id="insights" class="tab-section hidden">
          <h2>Performance Insights</h2>
          <p>AI recommends focusing on <strong>Mathematics</strong> and <strong>Programming Logic</strong> based on your recent results.</p>
        </section>

        <!-- ================= PROGRESS TRACKER ================= -->
        <section id="progress" class="tab-section hidden">
          <h2>Progress Tracker</h2>
          <p>Comparison charts and semester performance will be shown here.</p>
        </section>

        <!-- ================= NOTIFICATIONS ================= -->
        <section id="notifications" class="tab-section hidden">
          <h2>Notifications</h2>
          <ul class="notifications-list">
            <li>📢 New feedback from Prof. Garcia on IT 101.</li>
            <li>⚠️ Midterm results available for Math 201.</li>
          </ul>
        </section>

        <!-- ================= AI QUIZZES ================= -->
        <section id="quizzes" class="tab-section hidden">
          <h2>AI Quizzes</h2>
          <p>Take quizzes generated by your professors.</p>
          <button class="btn-primary">Start Quiz</button>
        </section>
      </div>
    </main>
  </div>
  <!-- Tab Highlighting & Smooth Scroll -->
  <? include '../../components/scroll.php'; ?>
</body>
</html>
